apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "k8sdevopscluster"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "k8sdevopscluster"
    spec:
      containers:
        - name: "k8sdevopscluster"
          image: "bnnair.azurecr.io/k8sdevopscluster"
          ports:
          - containerPort: 8080