apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "k8sdevops"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: "k8sdevops"
    spec:
      containers:
        - name: "k8sdevops"
          image: "bnnair.azurecr.io/k8sdevops"
          ports:
          - containerPort: 8080
